### ISSUE TITLE
Please connect a WiFi adapter and try again.

### ISSUE THREAD

**Issue by Morrigan-Ship** [MohitPimoli/Net-Ninja#1]
conntected to wifi and Lan cable at same time
WSL
ubuntu

**Comment by MohitPimoli** [comment]
Hi Morrigan-Ship,

Thank you so much for taking the time to report this issue! I appreciate your effort in helping to improve the tool. I’ll look into it and keep you posted on any updates or fixes.

Thanks again for your contribution!

Best,
Mohit Pimoli
